databases:
  - name: pdfcheckreader
    plan: free
    databaseName: pdfcheckreader
    user: pdfcheckreader

services:
  - type: web
    name: pdfcheckreader
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pdfcheckreader
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
