databases:
  - name: pdf-check-reader
    plan: free
    databaseName: pdf-check-reader
    user: pdf-check-reader

services:
  - type: web
    name: pdf-check-reader
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pdf-check-reader
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
